
#ifndef TRANSPORT_STATE_H
#define TRANSPORT_STATE_H

#include <string>

namespace joby
{
	enum TransportState
	{
		TRANSPORT_STATE_IN_FLIGHT,
		TRANSPORT_STATE_ENTERING_WAIT_LIST,
		TRANSPORT_STATE_WAITING_TO_CHARGE,
		TRANSPORT_STATE_CHARGING,
		TRANSPORT_STATE_STARTING_FLIGHT,

		MAX_TRANSPORT_STATES
	};
} // joby namespace

#endif // TRANSPORT_STATE_H
